export const mockData = [
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    nextEpisode: "Ep 1097 airing in 18 hours",
    percentage: "88%",
    studio: "Toei Animation",
    type: "TV Show",
    genres: ["action", "adventure", "comedy"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    nextEpisode: "Ep 1098 airing in 1 day",
    percentage: "92%",
    studio: "Studio Pierrot",
    type: "TV Show",
    genres: ["action", "fantasy"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    nextEpisode: "Ep 1099 airing in 2 days",
    percentage: "80%",
    studio: "Bones",
    type: "TV Show",
    genres: ["drama", "mystery"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    nextEpisode: "Ep 1100 airing in 3 days",
    percentage: "75%",
    studio: "Madhouse",
    type: "TV Show",
    genres: ["horror", "thriller"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    nextEpisode: "Ep 1101 airing in 4 days",
    percentage: "85%",
    studio: "Production I.G",
    type: "TV Show",
    genres: ["sci-fi", "adventure"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    nextEpisode: "Ep 1102 airing in 5 days",
    percentage: "70%",
    studio: "Kyoto Animation",
    type: "TV Show",
    genres: ["romance", "slice of life"],
  },
];

export const rankedData = [
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 1,
    nextEpisode: "Ep 1097 airing in 18 hours",
    percentage: "88%",
    studio: "Toei Animation",
    type: "TV Show",
    genres: ["action", "adventure", "comedy"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 2,
    nextEpisode: "Ep 1098 airing in 1 day",
    percentage: "92%",
    studio: "Studio Pierrot",
    type: "TV Show",
    genres: ["action", "fantasy"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 3,
    nextEpisode: "Ep 1099 airing in 2 days",
    percentage: "80%",
    studio: "Bones",
    type: "TV Show",
    genres: ["drama", "mystery"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 4,
    nextEpisode: "Ep 1100 airing in 3 days",
    percentage: "75%",
    studio: "Madhouse",
    type: "TV Show",
    genres: ["horror", "thriller"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 5,
    nextEpisode: "Ep 1101 airing in 4 days",
    percentage: "85%",
    studio: "Production I.G",
    type: "TV Show",
    genres: ["sci-fi", "adventure"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 6,
    nextEpisode: "Ep 1102 airing in 5 days",
    percentage: "70%",
    studio: "Kyoto Animation",
    type: "TV Show",
    genres: ["romance", "slice of life"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 7,
    nextEpisode: "Ep 1102 airing in 5 days",
    percentage: "70%",
    studio: "Kyoto Animation",
    type: "TV Show",
    genres: ["romance", "slice of life"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 8,
    nextEpisode: "Ep 1102 airing in 5 days",
    percentage: "70%",
    studio: "Kyoto Animation",
    type: "TV Show",
    genres: ["romance", "slice of life"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 9,
    nextEpisode: "Ep 1102 airing in 5 days",
    percentage: "70%",
    studio: "Kyoto Animation",
    type: "TV Show",
    genres: ["romance", "slice of life"],
  },
  {
    image: "/image.jpg",
    alt: "image",
    title: "Title",
    rank: 10,
    nextEpisode: "Ep 1102 airing in 5 days",
    percentage: "70%",
    studio: "Kyoto Animation",
    type: "TV Show",
    genres: ["romance", "slice of life"],
  },
];
